
SELECT 
        t1.dtRef,
        t1.IdCliente,
        t1.QntTransacaoVida,  
        t1.QntTransacaoD7,  
        t1.QntTransacaoD14,  
        t1.QntTransacaoD28,  
        t1.QntTransacaoD56,  
        t1.QntDiasVida,  
        t1.QntdiaD7, 
        t1.QntdiaD14,  
        t1.QntdiaD28,  
        t1.QntdiaD56,  
        t1.SaldoVida,  
        t1.SaldoD7,  
        t1.SaldoD14,  
        t1.SaldoD28,  
        t1.SaldoD56, 
        t1.PontosPosVida,  
        t1.PontosPosD7,  
        t1.PontosPosD14,  
        t1.PontosPosD28,  
        t1.PontosPosD56,  
        t1.PontosNegVida,  
        t1.PontosNegD7,  
        t1.PontosNegD14,  
        t1.PontosNegD28,  
        t1.PontosNegD56,  
        t1.idadeBase,
        t1.QnttransacoesManha,  
        t1.QnttransacoesTarde,  
        t1.QnttransacoesNoite,  
        t1.PcttransacoesManha,  
        t1.PcttransacoesTarde,  
        t1.PcttransacoesNoite,  
        t1.QntTransacaoDiaVida, 
        t1.QntTransacaoDiaD7, 
        t1.QntTransacaoDiaD14, 
        t1.QntTransacaoDiaD28, 
        t1.QntTransacaoDiaD56, 
        t1.PctAtivacaoMau, 
        t1.AvgintervaloDias,  
        t1.AvgintervaloDiasD28, 
        t1.QnthorasVida, 
        t1.QnthorasD7,
        t1.QnthorasD14, 
        t1.QnthorasD28, 
        t1.QnthorasD56, 
        t1.QntTransacaoChatMessage,  
        t1.QntTransacaoListaPresenca,  
        t1.QntTransacaoTrocaStreamElements,  
        t1.QntTransacaoResgatarPonei,  
        t1.QntTransacaoPresencaStreak,  
        t1.QntTransacaoAirflowLover,  
        t1.QntTransacaoRLover,  
        t1.QntTransacaoReembolsoStreamElements,  
        t1.QntTransacaochurnmodel,  
        t1.QntTransacaorpg,  
        t1.PctTransacaoChatMessage, 
        t1.PctTransacaoListaPresenca, 
        t1.PctTransacaoTrocaStreamElements,  
        t1.PctTransacaoResgatarPonei, 
        t1.PctTransacaoPresencaStreak, 
        t1.PctTransacaoAirflowLover, 
        t1.PctTransacaoRLover, 
        t1.PctTransacaoReembolsoStreamElements, 
        t1.PctTransacaochurnmodel, 
        t1.PctTransacaorpg,
        t2.Freq,
        t2.DescLifeCycleAtual,
        t2.DescLifeCycleD28,
        t2.PctReborn,
        t2.PctCURIOSO,
        t2.PctZumbi,
        t2.PctFIEL,
        t2.PctDesencantada,
        t2.PctTurista,
        t2.PctReconquistado,
        t2.AvglifeCycle,
        t2.ratio,
        t3.qtdeCursosCompletos ,
        t3.qtdeCursosIncompletos ,
        t3.carreira ,
        t3.coletaDados2024 ,
        t3.dsDatabricks2024 ,
        t3.dsPontos2024 ,
        t3.estatistica2024    ,
        t3.estatistica2025  ,
        t3.github2024 ,
        t3.github2025 ,
        t3.iaCanal2025 ,
        t3.lagoMago2024,
        t3.machineLearning2025,
        t3.matchmakingTramparDeCasa2024,
        t3.ml2024 ,
        t3.mlflow2025,
        t3.pandas2024,
        t3.pandas2025,
        t3.python2024,
        t3.python2025,
        t3.sql2020,
        t3.sql2025,
        t3.streamlit2025,
        t3.tramparLakehouse2024,
        t3.tseAnalytics2024,
        t3.qtdDiasUltiAtividade

FROM fs_transacional as t1
LEFT JOIN fs_life_cycle as t2
ON t1.IdCliente = t2.IdCliente
AND t1.dtRef = t2.dtRef
LEFT JOIN fs_education as t3 
ON t1.IdCliente = t3.IdCliente
AND t1.dtRef = t3.dtRef

WHERE t1.dtRef = (SELECT MAX(dtRef) FROM fs_transacional)

